openapi: 3.0.0
info:
  title: JSONPlaceholder API - Documentación Mejorada
  description: Documentación profesional de los endpoints REST para el examen 001.
  version: 1.0.0
  contact:
    name: API Support
    email: support@jsonplaceholder.typicode.com

servers:
  - url: https://jsonplaceholder.typicode.com
    description: Servidor de producción

tags:
  - name: Posts
    description: Operaciones relacionadas con publicaciones
  - name: Comments
    description: Comentarios asociados a publicaciones
  - name: Albums
    description: Administración de álbumes
  - name: Photos
    description: Gestión de fotos
  - name: Todos
    description: Gestión de tareas pendientes
  - name: Users
    description: Información de usuarios registrados

paths:

  # ==================== POSTS ====================
  /posts:
    get:
      tags: [Posts]
      summary: Obtener todos los posts
      description: Retorna la lista completa de publicaciones.
      responses:
        '200':
          description: Lista de posts obtenida exitosamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'

    post:
      tags: [Posts]
      summary: Crear un nuevo post
      description: Crea una nueva publicación.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostInput'
      responses:
        '201':
          description: Post creado correctamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'

  /posts/{id}:
    get:
      tags: [Posts]
      summary: Obtener un post por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Post encontrado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '404':
          description: Post no encontrado.

    put:
      tags: [Posts]
      summary: Actualizar un post completo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '200':
          description: Post actualizado correctamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'

    patch:
      tags: [Posts]
      summary: Actualizar parcialmente un post
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "Título actualizado"
      responses:
        '200':
          description: Post actualizado parcialmente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'

    delete:
      tags: [Posts]
      summary: Eliminar un post por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Post eliminado correctamente.
        '404':
          description: Post no encontrado.

  # ==================== COMMENTS ====================
  /comments:
    get:
      tags: [Comments]
      summary: Obtener todos los comentarios
      parameters:
        - name: postId
          in: query
          schema:
            type: integer
          description: Filtrar comentarios por ID de post.
      responses:
        '200':
          description: Lista de comentarios obtenida correctamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'

    post:
      tags: [Comments]
      summary: Crear un nuevo comentario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommentInput'
      responses:
        '201':
          description: Comentario creado correctamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'

  # ==================== ALBUMS ====================
  /albums:
    get:
      tags: [Albums]
      summary: Obtener todos los álbumes
      responses:
        '200':
          description: Lista de álbumes obtenida correctamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Album'

    post:
      tags: [Albums]
      summary: Crear un nuevo álbum
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AlbumInput'
      responses:
        '201':
          description: Álbum creado correctamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Album'

  /albums/{id}:
    get:
      tags: [Albums]
      summary: Obtener un álbum por ID
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Álbum encontrado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Album'
        '404':
          description: Álbum no encontrado.

  # ==================== PHOTOS ====================
  /photos:
    get:
      tags: [Photos]
      summary: Obtener todas las fotos
      parameters:
        - name: albumId
          in: query
          schema:
            type: integer
          description: Filtrar fotos por ID de álbum.
      responses:
        '200':
          description: Lista de fotos obtenida correctamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Photo'

  # ==================== TODOS ====================
  /todos:
    get:
      tags: [Todos]
      summary: Obtener todas las tareas
      responses:
        '200':
          description: Lista de tareas obtenida correctamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'

    post:
      tags: [Todos]
      summary: Crear una nueva tarea
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoInput'
      responses:
        '201':
          description: Tarea creada correctamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'

  /todos/{id}:
    get:
      tags: [Todos]
      summary: Obtener una tarea por ID
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Tarea encontrada.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '404':
          description: Tarea no encontrada.

  # ==================== USERS ====================
  /users:
    get:
      tags: [Users]
      summary: Obtener todos los usuarios
      responses:
        '200':
          description: Lista de usuarios obtenida correctamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

  /users/{id}:
    get:
      tags: [Users]
      summary: Obtener un usuario por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Usuario encontrado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Usuario no encontrado.

components:
  schemas:

    # ---------- POSTS ----------
    Post:
      type: object
      properties:
        userId:
          type: integer
        id:
          type: integer
        title:
          type: string
        body:
          type: string

    PostInput:
      type: object
      required: [title, body, userId]
      properties:
        title:
          type: string
        body:
          type: string
        userId:
          type: integer

    # ---------- COMMENTS ----------
    Comment:
      type: object
      properties:
        postId:
          type: integer
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        body:
          type: string

    CommentInput:
      type: object
      required: [postId, name, email, body]
      properties:
        name: { type: string }
        email: { type: string }
        body: { type: string }
        postId: { type: integer }

    # ---------- ALBUMS ----------
    Album:
      type: object
      properties:
        userId: { type: integer }
        id: { type: integer }
        title: { type: string }

    AlbumInput:
      type: object
      required: [title, userId]
      properties:
        userId: { type: integer }
        title: { type: string }

    # ---------- PHOTOS ----------
    Photo:
      type: object
      properties:
        albumId: { type: integer }
        id: { type: integer }
        title: { type: string }
        url: { type: string }
        thumbnailUrl: { type: string }

    # ---------- TODOS ----------
    Todo:
      type: object
      properties:
        userId: { type: integer }
        id: { type: integer }
        title: { type: string }
        completed: { type: boolean }

    TodoInput:
      type: object
      required: [title, completed, userId]
      properties:
        title: { type: string }
        completed: { type: boolean }
        userId: { type: integer }

    # ---------- USERS ----------
    User:
      type: object
      properties:
        id: { type: integer }
        name: { type: string }
        username: { type: string }
        email: { type: string }
        address:
          $ref: '#/components/schemas/Address'
        phone: { type: string }
        website: { type: string }
        company:
          $ref: '#/components/schemas/Company'

    Address:
      type: object
      properties:
        street: { type: string }
        suite: { type: string }
        city: { type: string }
        zipcode: { type: string }
        geo:
          $ref: '#/components/schemas/Geo'

    Geo:
      type: object
      properties:
        lat: { type: string }
        lng: { type: string }

    Company:
      type: object
      properties:
        name: { type: string }
        catchPhrase: { type: string }
        bs: { type: string }
